### ISSUE TITLE
Hive JDBC support

### ISSUE THREAD

**Issue by jayeshagwan1** [tokern/piicatcher#54]
Does piicatcher support Hive ?

**Comment by vrajat** [comment]
Not yet. It can be added using pyhive: https://github.com/dropbox/PyHive

Are you open to contributing the integration? I can guide you through it.

**Comment by jayeshagwan1** [comment]
I am interested in contributing.

**Comment by vrajat** [comment]
Thanks!
Here are some guidelines on how to get started:

### Install a developer version of piicatcher

1. Fork the repo.
2. Instructions are here: https://tokern.io/docs/piicatcher/development

### Hive installation

I am not sure about your tech setup. A web search should provide a lot of websites with instrutions to setup Hive. 

### Load data into Hive

I use a couple of simple datasets:
1. https://github.com/tokern/piicatcher/blob/master/tests/test_databases.py#L19
2. https://github.com/tokern/piicatcher/blob/master/tests/samples/sample-data.csv

### Add pyhive

Add pyhive as a requirement in requirements.txt

Rerun pipenv update to install pyhive.

### Write a explorer

An [explorer](https://github.com/tokern/piicatcher/blob/master/piicatcher/explorer/explorer.py) is the base class for supporting different types of technologies. 
You can use [AWS Explorer](https://github.com/tokern/piicatcher/blob/master/piicatcher/explorer/aws.py) as an example. 

You'll have to:
1. Create a new python file - *hive.py* - for example.
2. Implement a *cli* function.
3. Implement a *HiveExplorer* class similar to *AthenaExplorer*
4. Change all the code in the functions to make it work with hive. For example all the queries have to be changed. Use pyhive instead of pyathena and so on.


I can answer any questions while you develop.

**Comment by jayeshagwan1** [comment]
Thanks @vrajat. Will follow the above steps. If any issue, will let you know.

**Comment by jayeshagwan1** [comment]
Above steps were followed. After running the command **piicatcher --config hiveconfig.ini hive**
getting below error :
![image](https://user-images.githubusercontent.com/616970/73274446-93cd4c00-420b-11ea-9c96-fd076896ecfe.png)

It seems its issue on windows system while installing pyhive.

**Comment by vrajat** [comment]
Try adding sasl to requirements.txt

**Comment by jayeshagwan1** [comment]
![image](https://user-images.githubusercontent.com/616970/73327919-c6179180-427d-11ea-8ead-966d2ee92113.png)

**Comment by vrajat** [comment]
Does this help ? https://stackoverflow.com/a/58167572

**Comment by jayeshagwan1** [comment]
Thanks. Now facing :

![image](https://user-images.githubusercontent.com/616970/73332399-a20f7c80-428c-11ea-9689-87ed8e08abbd.png)

**Comment by jayeshagwan1** [comment]
https://github.com/dropbox/PyHive/issues/69

**Comment by jayeshagwan1** [comment]
https://community.cloudera.com/t5/Support-Questions/pyhive-connection-error-thrift-transport-TTransport/td-p/206372

**Comment by vrajat** [comment]
Which version of Hive have you installed ? Are you using HiveServer2 ?

**Comment by jayeshagwan1** [comment]
Hive2

**Comment by vrajat** [comment]
Do you use HiveServer2 ?

**Comment by jayeshagwan1** [comment]
yes

**Comment by vrajat** [comment]
Can you try connecting using pyhive in a python console ? Let's make sure
pyhive is working. For example,


conn = hive.Connection(host=host_name, port=port, username=user,
password=password,
                           database=database)

    cur = conn.cursor()

    cur.execute('select item_sk,reason_sk, account_credit from returns
limit 5')

    result = cur.fetchall()

    return result

**Comment by jayeshagwan1** [comment]
Now able to connect to hiveserver2. But getting below error:


raise ValueError("Password should be set if and only if in LDAP or CUSTOM mode; "                      ValueError: Password should be set if and only if in LDAP or CUSTOM mode; Remove password or use one of th ose modes
--


Currently I am passing auth='NOSASL' in connection. If I pass auth='Custom or none' then getting this error:

![image](https://user-images.githubusercontent.com/616970/73713777-9b718100-4734-11ea-963f-1fe20eb8a280.png)

**Comment by vrajat** [comment]
Can you confirm if these are errors when you try to connect to hive through python console ? No PIICatcher involved ? 

Can you confirm if you can connect to Hive and run queries from python console ?

**Comment by jayeshagwan1** [comment]
Sure. Will confirm. I think there similar open issues with pyhive also. Do we have other option for pyhive ?

**Comment by vrajat** [comment]
1. https://github.com/cloudera/impyla
2. https://dwgeek.com/steps-to-connect-hiveserver2-from-python-using-hive-jdbc-drivers.html/

1. is probably the better option

**Comment by jayeshagwan1** [comment]
There is some issue with pyhive. I have tried with python, but still getting same error.

![image](https://user-images.githubusercontent.com/616970/73718790-78020280-4743-11ea-83dc-f2e17aba730b.png)

**Comment by jayeshagwan1** [comment]
Is it specific to OS ? Haven't tried with linux or ubuntu yet.

**Comment by vrajat** [comment]
I am not sure. I've used in Centos and it worked. That was for a specific configuration of hive. OS or the configuration of python/hive can be the problem. Dont know how to help remotely with no knowledge about the setup.

**Comment by vrajat** [comment]
Can you try impyla ?

**Comment by jayeshagwan1** [comment]
Is this uses impala ?

**Comment by jayeshagwan1** [comment]
I am trying on centOS, but getting this error:

 [Errno 14] problem making ssl connection
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: bintray--sbt-rpm. Please verify its path and try again

So could not install anything. Tried couple of things for ssl but its not working

**Comment by vrajat** [comment]
Impyla is supposed to work with hiveserver2 as well.

That seems like a rpm issue and not a pyhive issue ?

**Comment by vrajat** [comment]
ftw superset uses pyhive. https://github.com/apache/incubator-superset/blob/master/superset/db_engine_specs/hive.py#L71

There are also hive related issues but in general it works. I still think there is something about your installation that pyhive does not work with.

**Comment by jayeshagwan1** [comment]
I will start working on Hive from next week and keep you posted.

**Comment by zer0pool** [comment]
@jayeshagwan1 hello. I am wondering how this implementation go.  it would be great if this feature can be added soon.

**Comment by vrajat** [comment]
There hasnt been any progress on this feature. IIRC @jayeshagwan1 got stuck in installing a test Hive cluster. @zer0pool will you be able to help out?
